[theme]
primaryColor="#FF4B4B"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000"

[server]
headless = true

[browser]
gatherUsageStats = false

[ui]
# FORCE SHOW SIDEBAR FOR MULTIPAGE APPS
hideSidebarNav = false
